#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

help() {
    cat <<-EOF
Usage: gh todo

[GitHub CLI] extension for todo list manager via GitHub issues

Actions:
    init        Create \`todo\` repo
    add         Create a todo
    list        List todo

Examples:
    gh todo add abc
EOF
}

date=$(date -u +"%Y-%m-%d")
repo="yuler/test-todo"

get_issue_id() {
    echo $(gh issue list --search "$date" --json "number" --jq ".[0].number" --repo $repo)
}

init() {
    exec gh repo create --confirm --private todo
}

add() {
    input="$1"
    issue_id=$(get_issue_id)
    if [[ -z $issue_id ]]; then
        exec gh issue create --title $date --body "- [ ] $input" --repo $repo
    else
        body=$(gh issue list --search "$date" --json "body" --jq ".[0].body" --repo $repo)
        body=$(echo -e "$body\n- [ ] $input")
        exec gh issue edit $issue_id --body "$body" --repo $repo
    fi
}

list() {
    issue_id=$(get_issue_id)
    if [[ -z $issue_id ]]; then
        echo "No plans for today yet."
    else
        exec gh issue view $issue_id --repo $repo
    fi
}

# main
if [[ $# -eq 0 ]]; then
    list
    exit 0
fi

while [ $# -gt 0 ]; do
    case "$1" in
    -h | --help)
        help
        exit 0
        ;;
    init)
        init
        shift
        ;;
    add)
        if [[ -z "$2" ]]; then
            echo -n "Add:"
            read -e -r input
        else
            shift
            input=$*
        fi
        add "$input"
        ;;
    *)
        help >&2
        exit 1
        ;;
    esac
    shift
done
