#!/usr/bin/env bash
set -eo pipefail

usage() {
    cat <<-EOF
Usage: gh todo

[GitHub CLI] extension for todo list manager via GitHub issues

Actions:
    init        Create \`todo\` repo
    home        Open \`issues\` in browser
    add         Add todo item
    view/edit   Open \`issue\` in browser
    done        Close \`issue\`
    list        Show todo list

Options:
    --version   Show version
    --help      Show help for command
    --scope     TODO scope, default: today(yyyy-MM-dd).
                Support [yesterday, tomorrow, week, month, year].
                Any other will be used directly as issue title.
Examples:
    gh todo add abc
EOF
}

version="0.4.3"

repo="$(gh config get -h github.com user)/todo"

if [ -n "$GH_TODO_REPO" ]; then
    repo="$GH_TODO_REPO"
fi

# parse `--scope` option
POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"

    case $key in
    --scope)
        scope="$2"
        shift # past argument
        shift # past value
        ;;
    *)                     # unknown option
        POSITIONAL+=("$1") # save it in an array for later
        shift              # past argument
        ;;
    esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

get_issue_id() {
    gh issue list --search "$issue_title" --json "number" --jq ".[0].number" --repo $repo
}

init() {
    exec gh repo create --confirm --private $@ $repo
}

home() {
    gh issue list --web --repo $repo
}

add() {
    input="$1"
    issue_id=$(get_issue_id)
    if [[ -z $issue_id ]]; then
        exec gh issue create --title "$issue_title" --body "- [ ] $input" --repo $repo
    else
        body=$(gh issue view $issue_id --json "body" --jq ".body" --repo $repo)
        body=$(echo -e "$body\n- [ ] $input")
        exec gh issue edit $issue_id --body "$body" --repo $repo
    fi
}

edit() {
    issue_id=$(get_issue_id)
    if [[ -z $issue_id ]]; then
        echo "No plans for $issue_title yet."
    fi
    exec gh issue view $issue_id --repo $repo --web
}

_done() {
    issue_id=$(get_issue_id)
    if [[ -z $issue_id ]]; then
        echo "No plans for $issue_title yet."
    else
        exec gh issue close $issue_id --repo $repo
    fi
}

list() {
    issue_id=$(get_issue_id)
    if [[ -z $issue_id ]]; then
        echo "No plans for $issue_title yet."
    else
        exec gh issue view $issue_id --repo $repo
    fi
}

# main
if [[ $# -eq 0 ]]; then
    list
    exit 0
fi

issue_title=$(date +"%Y-%m-%d")
# get issue id by `--scope`
if [ -n "$scope" ]; then
    case "$scope" in
    yesterday)
        issue_title=$(date -v-1d +"%Y-%m-%d")
        ;;
    tomorrow)
        issue_title=$(date -v+1d +"%Y-%m-%d")
        ;;
    week)
        issue_title="Week: $(date -v -Mon +"%Y-%m-%d") ~ $(date -v -Mon -v+6d +"%Y-%m-%d")"
        ;;
    month)
        issue_title="Month: $(date +"%Y-%m")"
        ;;
    year)
        issue_title="Year: $(date +"%Y")"
        ;;
    *)
        issue_title=$scope
        ;;
    esac
fi

while [ $# -gt 0 ]; do
    case "$1" in
    --version)
        echo $version
        exit 0
        ;;
    --help)
        usage
        exit 0
        ;;
    init)
        shift
        init $@
        ;;
    home)
        shift
        home
        ;;
    add)
        if [[ -z "$2" ]]; then
            echo -n "[Enter]: "
            read -e -r input
        else
            shift
            input=$*
        fi
        add "$input"
        ;;
    view | edit)
        shift
        edit
        ;;
    done)
        shift
        _done
        ;;
    list)
        shift
        list
        ;;
    *)
        usage >&2
        exit 1
        ;;
    esac
    shift
done
